config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  get 'dashboard/index'

#, shallow: true

  devise_for :users
  resources :clients do
    resources :packages
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :packages, dependent: :destroy

  accepts_nested_attributes_for :packages

  # Search
  def self.search(search)
		key = "%#{search}%"
    if search
      where(["first_name LIKE :search OR second_name LIKE :search OR last_name LIKE :search OR second_last_name LIKE :search OR principal_phone LIKE :search OR cellphone LIKE :search OR email LIKE :search OR birth LIKE :search OR address LIKE :search OR postal_code LIKE :search OR city LIKE :search OR state LIKE :search OR emergency_contact_full_name LIKE :search OR emergency_contact_address LIKE :search OR emergency_contact_phone LIKE :search", search: key])
    else
      all
    end
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.search(params[:search]).paginate(page: params[:page], per_page: 6).order('created_at DESC')
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Cliente guardado.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Cliente actualizado.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Cliente elimidado!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :second_name, :last_name, :second_last_name, :principal_phone, :cellphone, :email, :birth, :address, :postal_code, :city, :state, :emergency_contact_full_name, :emergency_contact_address, :emergency_contact_phone)
    end

    def search_params
      params.require(:search).permit(:first_name, :second_name, :last_name, :second_last_name, :principal_phone, :cellphone, :email, :birth, :address, :postal_code, :city, :state, :emergency_contact_full_name, :emergency_contact_address, :emergency_contact_phone)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error")%> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
  <div class="panel-body">
    <form class="form-horizontal">
      <fieldset>
        <legend class="text-center">Ingrese aquí los datos</legend>

        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">1. Datos del Cliente</h3>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-lg-6 control-label">Primer Nombre</label>
              <div class="col-lg-12">
                <%= f.text_field :first_name, :class => "form-control", :placeholder => "Primer Nombre", :autofocus => true %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-6 control-label">Segundo Nombre</label>
              <div class="col-lg-12">
                <%= f.text_field :second_name, :class => "form-control", :placeholder => "Segundo Nombre" %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-6 control-label">Primer Apellido</label>
              <div class="col-lg-12">
                <%= f.text_field :last_name, :class => "form-control", :placeholder => "Primer Apellido" %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-6 control-label">Segundo Apellido</label>
              <div class="col-lg-12">
                <%= f.text_field :second_last_name, :class => "form-control", :placeholder => "Segundo Apellido" %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-6 control-label">Fecha de Nacimiento</label>
              <div class="col-lg-12">
                <%= f.date_select :birth, start_year: 1915, :class => "form-control" %>
              </div>
            </div>
          </div>
        </div>

        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">2. Datos de contacto</h3>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-lg-6 control-label">Dirección</label>
              <div class="col-lg-12">
                <%= f.text_field :address, :class => "form-control", :placeholder => "Dirección" %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-6 control-label">Código Postal</label>
              <div class="col-lg-12">
                <%= f.text_field :postal_code, :class => "form-control", :placeholder => "Código Postal" %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-6 control-label">Ciudad</label>
              <div class="col-lg-12">
                <%= f.text_field :city, :class => "form-control", :placeholder => "Ciudad" %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-6 control-label">Estado</label>
              <div class="col-lg-12">
                <%= f.text_field :state, :class => "form-control", :placeholder => "Estado" %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-6 control-label">Teléfono Principal</label>
              <div class="col-lg-12">
                <%= f.text_field :principal_phone, :class => "form-control", :placeholder => "Teléfono Principal" %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-6 control-label">Teléfono Celular</label>
              <div class="col-lg-12">
                <%= f.text_field :cellphone, :class => "form-control", :placeholder => "Teléfono Celular" %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-6 control-label">Email</label>
              <div class="col-lg-12">
                <%= f.text_field :email, :class => "form-control", :placeholder => "Email" %>
              </div>
            </div>
          </div>
        </div>

        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">3. Datos del contacto de emergencia</h3>
          </div>
          <div class="panel-body">
            <div class="form-group has-warning">
              <label class="col-lg-6 control-label">Nombre del Contacto de Emergencia</label>
              <div class="col-lg-12">
                <%= f.text_field :emergency_contact_full_name, :class => "form-control", :placeholder => "Nombre del Contacto de Emergencia" %>
              </div>
            </div>
            <div class="form-group has-warning">
              <label class="col-lg-6 control-label">Dirección del Contacto de Emergencia</label>
              <div class="col-lg-12">
                <%= f.text_field :emergency_contact_address, :class => "form-control", :placeholder => "Dirección del Contacto de Emergencia" %>
              </div>
            </div>
            <div class="form-group has-warning">
              <label class="col-lg-6 control-label">Teléfono del Contacto de Emergencia</label>
              <div class="col-lg-12">
                <%= f.text_field :emergency_contact_phone, :class => "form-control", :placeholder => "Teléfono del Contacto de Emergencia" %>
              </div>
            </div>
          </div>
        </div>

      </fieldset>
      <br />
      <div class="actions">
        <%= f.submit 'Ingresar datos', :class => "btn btn-success center-block" %>
      </div>
    </form>
  </div>
</div>
<br />
<% end %>

app/views/clients/_paginate.html.erb
<br />
  <div class="text-center">
    <%= will_paginate @clients, previous_label: "Anterior", next_label: "Siguiente", renderer: BootstrapPagination::Rails %>
  </div>
<br />

app/views/clients/_search.html.erb
<!-- Search -->
<div class="row search">
  <div class="col-xs-12 pull-right">
    <%= form_tag clients_path, :method => "get" do %>
    <p>
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Busca un cliente o busca cualquier campo del cliente, ej. email, teléfono, dirección, etc." %>
    </p>
    <p class="pull-right">
      <%= submit_tag "Buscar", class: 'btn btn-default' %>
    </p>
    <% end %>
  </div>
</div>
<!-- ./Search -->

app/views/clients/edit.html.erb
<div class="container">
  <h1 class="text-center">Editar cliente</h1>
  <hr />
  <%= render 'form' %>
  <br />
  <div class="btn-group btn-group-justified">
    <%= link_to 'Regresar a clientes ingresados', clients_path, :class => "btn btn-default" %>
    <%= link_to 'Ir a vista del cliente', @client, :class => "btn btn-primary" %>
  </div>
</div>

app/views/clients/index.html.erb
<div class="container">
  <h1 class="text-center">Clientes Ingresados</h1>
  <hr />
  <%= render 'search' %>
  <hr />
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th class="text-center">ID #</th>
        <th class="text-center">Nombre cliente</th>
        <th class="text-center">Teléfono principal</th>
        <th class="text-center">Email</th>
        <th class="text-center">Acciones</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><%= client.id %></td>
          <td><%= client.first_name.capitalize %> <%= client.second_name.capitalize %> <%= client.last_name.capitalize %> <%= client.second_last_name.capitalize %></td>
          <td><%= client.principal_phone %></td>
          <td><%= client.email %></td>
          <td class="text-center">
            <%= link_to client, :class => "btn btn-info btn-xs", title: 'Ver cliente' do %>
              <%= fa_icon "eye", :class => "btn-fa" %>
            <% end %>
          </td>
          <td class="text-center">
            <%= link_to new_client_package_path(client_id: client), :class => "btn btn-success btn-xs", title: 'Añadir un paquete' do %>
              <%= fa_icon "plus", :class => "btn-fa"  %>
            <% end %>
          </td>
          <td class="text-center">
            <%= link_to edit_client_path(client), :class => "btn btn-warning btn-xs", title: 'Editar cliente' do %>
              <%= fa_icon "edit", :class => "btn-fa" %>
            <% end %>
          </td>
          <td class="text-center">
            <%= link_to client, method: :delete, data: { confirm: '¿Estas seguro? esta acción no se puede deshacer!' }, :class => "btn btn-danger btn-xs", title: 'Eliminar cliente' do %>
              <%= fa_icon "trash", :class => "btn-fa" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= render 'paginate' %>

  <%= link_to 'Ingresar cliente', new_client_path, :class => "btn btn-success btn-lg btn-block" %>
</div>

app/views/clients/new.html.erb
<div class="container">
  <h1 class="text-center">Nuevo Cliente</h1>
  <hr />
  <%= render 'form' %>
  <br />
  <div class="btn-group btn-group-justified">
    <%= link_to 'Regresar a clientes ingresados', clients_path, :class => "btn btn-default" %>
  </div>
</div>

app/views/clients/show.html.erb
<div class="container">
  <h1 class="text-center">Información del cliente</h1>
  <hr />




  <table class="table table-striped table-hover ">
    <thead>
      <tr class="info">
        <th>
          Información
        </th>
        <th>
          Datos del Cliente
        </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          Nombre:
        </td>
        <td>
          <%= @client.first_name.capitalize %> <%= @client.second_name.capitalize %> <%= @client.last_name.capitalize %> <%= @client.second_last_name.capitalize %>
        </td>
      </tr>
      <tr>
        <td>
          Teléfono principal:
        </td>
        <td>
          <%= @client.principal_phone %>
        </td>
      </tr>
      <tr>
        <td>
          Teléfono celular:
        </td>
        <td>
          <%= @client.cellphone %>
        </td>
      </tr>
      <tr>
        <td>
          Email:
        </td>
        <td>
          <%= @client.email %>
        </td>
      </tr>
      <tr>
        <td>
          Fecha de nacimiento:
        </td>
        <td>
          <%= @client.birth %>
        </td>
      </tr>
      <tr>
        <td>
          Dirección:
        </td>
        <td>
          <%= @client.address.capitalize %>
        </td>
      </tr>
      <tr>
        <td>
          Código Postal:
        </td>
        <td>
          <%= @client.postal_code %>
        </td>
      </tr>
      <tr>
        <td>
          Ciudad:
        </td>
        <td>
          <%= @client.city.capitalize %>
        </td>
      </tr>
      <tr>
        <td>
          Estado:
        </td>
        <td>
          <%= @client.state.capitalize %>
        </td>
      </tr>
    </tbody>
  </table>


















  <table class="table table-striped table-hover ">
    <thead>
      <tr class="info">
        <th>
          Información
        </th>
        <th>
          Datos del contacto de emergencia
        </th>
      </tr>
    </thead>
    <tbody>
      <tr class="warning">
        <td>
          Contacto de emergencia:
        </td>
        <td>
          <%= @client.emergency_contact_full_name.upcase %>
        </td>
      </tr>
      <tr class="warning">
        <td>
          Dirección contacto:
        </td>
        <td>
          <%= @client.emergency_contact_address.capitalize %>
        </td>
      </tr>
      <tr class="warning">
        <td>
          Teléfono de contacto:
        </td>
        <td>
          <%= @client.emergency_contact_phone %>
        </td>
      </tr>
    </tbody>
  </table>
  <br />
  <div class="btn-group btn-group-justified">
    <%= link_to 'Regresar a clientes', clients_path, :class => "btn btn-default" %>
    <%= link_to 'Editar cliente', edit_client_path(@client), :class => "btn btn-warning" %>
    <%= link_to 'Mostrar paquetes', client_packages_path(@client), :class => "btn btn-success" %>
  </div>
</div>